### ISSUE TITLE
Add an example how to format names of feature branches

### ISSUE THREAD

**Issue by zummenix** [Saritasa/ios-development-guides#11]
For commit messages we use the following format: `{commit message} {task id}`
It's better to have the same structure for branches: `feature/{short task description}-{task id}`
Example:
```
feature/prepare-for-appstore-#85593
```
What do you think?

**Comment by AgapovOne** [comment]
Also we can add naming conventions for git flow.
Like this:
Development branch: `dev/develop/development`
Production branch: `master/production`
Feature branch: `feature/{description}-{task id}

Also, some information about releases - tag naming, and do we need a branch for releases only?

**Comment by zummenix** [comment]
`master` and `develop` are defaults when we create a repository. Don't see any reason to change them.
Good point about tag naming.

**Comment by akhatmullin** [comment]
Git create only one branch for new repository. It's a `master` branch. This branch is tracking by default.
We can make more branches like `development`, `staging`, `production`, etc but actually we use only one branch - `develop`. Let's make this process easier! I think we should use `master` branch.

The same structure for branches is a really good idea, but I think we don't need replace description and id. We can use old scheme `feature/task_number-short_task_description`. Also in my opinion we should use different paths for different tasks: `feature/`, `fixes/`, etc.

What do you think about using git tags for versions?

**Comment by zummenix** [comment]
The reason I'm thinking about `feature/{short task description}-{task id}` format is because we use analogous for commit messages. It's easy to remember.

I'm not sure about `fixes/` path. Git flow in SourceTree supports `hotfix/` but I haven't used it.

On other projects I was using build numbers or/and versions of an app. In general I prefer build numbers because they change often.

**Comment by akhatmullin** [comment]
I think we don't have any reasons for writing task id in commit messages.
SourceTree and Terminal support any path name for branches. It's a simple logic: separating fixing bugs and making new bugs. :) We don't place models and view controllers in the same folder, right?

**Comment by AgapovOne** [comment]
I think we should generally use git flow suggestion about develop/master branch and use `develop` as a main branch. That would be common to any developer.
As for `hotfix/` branch, we should decide which type of branch to use based on a task we are doing. `hotfix/` would be preferred name based on git flow suggestions, again.

Tags for a commit could mean an App Store release + I think we should merge into `master/` every tagged release commit.

So that's my suggestions (because git-flow is a well-known branching model):
- `develop` as a main branch
- `master` for tagged releases
- `hotfix/` for bugfixes tasks
- `feature/` for feature tasks
- tags for releases with a naming of `0.1.1(20)` as we use always in Xcode

UpSource can link Task number to Jira - so we definitely should use it in commit messages :)

**Comment by akhatmullin** [comment]
@AgapovOne Branches `develop` and `master` will contain identical commits. Why are we need two branches?
Ok. Who don't use SourceTree? Only me? %)

**Comment by AgapovOne** [comment]
If we look into `master` we can see only releases there. It would be convenient to find old released versions. Also if we want to build and distribute latest release - all we need is a branch switch.

**Comment by zummenix** [comment]
> I think we don't have any reasons for writing task id in commit messages.

I agree if we have task id for a branch. If we need to fix something small there is no point to make three steps (create separate branch, commit and merge). Just commit as `{commit message} {task id}`

`master` branch should contain only release commits.

**Comment by zummenix** [comment]
> Ok. Who don't use SourceTree? Only me? %)

I don't use it when I work alone on my side projects. )

So, to summarize:
- Use git flow (SourceTree supports it out of the box)
- `develop` as a main branch
- `master` for tagged releases
- `feature/{short task description}-{task id}` format for feature branches, commits without task id
- `{commit message} {task id}` format for single commits

**Comment by AgapovOne** [comment]
Again about naming :)

We have a rule about adding `Task: #{task id}` to the end of commit. When we're using a branch with task id it would be easier to see which task we need by looking at the branch. It is definitely easier to look into first letters of a branch name. 
Also, when we have a full list of branches like
```
feature/A-10-collections
feature/A-11-updates
feature/A-12-ui-for-module
```
It would be easier to sort them by task id.

What do you think?

**Comment by zummenix** [comment]
These are valid points.
