### ISSUE TITLE
Add a note about tag format: {major}.{minor}.{patch}({build number})

### ISSUE THREAD

**Issue by akhatmullin** [Saritasa/ios-development-guides#12]
I think we need the same style for build & version numbers.
We can use this scheme: 1.2.3 (456)
1 - It's a version of the app (example: 1.0.0 for the first release). Should be increased if we make global changes in the all app (full redesign).
2 - It's a subversion. Should be increased when we add new feature in the app.
3 - This number we should increase if we make bug fixes in the app for current subversion.
456 - build number, should be an integer value and increased after any changes.

https://en.wikipedia.org/wiki/Software_versioning

**Comment by AgapovOne** [comment]
Yes, this is reasonable. As semantic versioning suggests for any software.
MAJOR.MINOR.PATCH
http://semver.org/

**Comment by zummenix** [comment]
I'm afraid semantic versioning doesn't work for apps. Version of the app is important for users. For developers it's less important.
Ok, let's make it a rule.

**Comment by akhatmullin** [comment]
@zummenix In my opinion it's important for development.
Sometimes I see a version and build number on splash screens. When client say that he has found a bug in the version we can find this version by tags in commits.
Maybe it's my mistake, but it can be really useful. We should check it. :-)

**Comment by zummenix** [comment]
Yeah, I meant that sometimes we need to have format like: `{major}.{minor}` for appstore
