### ISSUE TITLE
Define naming conventions for image assets

### ISSUE THREAD

**Issue by zummenix** [Saritasa/ios-development-guides#21]

**Comment by zummenix** [comment]
- use prefixes, i.e. `bg` (background), `ic` (icon)
- use `_` as a word separator
- clear name. If an image belongs to a module, i.e. unique to a module, then we need to add the name of a module.

Examples:
- `ic_cancel`
- `ic_pathway_questions_cancel`
- `bg_dropdown`

Open question: Do we need to use grouping in .xcassets? In my opinion we don't since usage of the name of a module already gives quite good grouping.

**Comment by akhatmullin** [comment]
I think we need two prefixes sometimes. For example if we have background image for button: `bg_btn_cancel`. Also we should use postfixes for UI elements with different states: `bg_btn_cancel_normal` or `bg_btn_cancel_highlighted`etc.

One more idea. Can design team use this naming rules? If they can we shouldn't change assets' names and should use search in assets folders before import. It's opportunity to exclude duplicating image asset files in a project.

**Comment by zummenix** [comment]
The `btn` prefix seems redundant to me but I don't have strong opinion against it.
> Also we should use postfixes for UI elements with different states: `bg_btn_cancel_normal` or `bg_btn_cancel_highlighted` etc.

Good point, I agree.

I'm not sure about design team. They don't know how we will divide the app to modules so they can't follow our conventions properly.
