### ISSUE TITLE
Code generators (SwiftGen, Sourcery)

### ISSUE THREAD

**Issue by AgapovOne** [Saritasa/ios-development-guides#23]
Tools that generate tools based on template can be helpful in projects with somewhat big codebase (models with a lot of properties, equatable for structs, etc.). We can use tools like [Sourcery](https://github.com/krzysztofzablocki/Sourcery) to simplify development. However, I don't really see projects where we should write templates and it will minimize dev time.

Anyway, there are great tools that uses these templates already. One of them is [SwiftGen](https://github.com/SwiftGen/SwiftGen). It can help us with **storyboards**, localization, colors, fonts, and images (swift3 also has image literals that are great and don't need any codegen).

I see it as a great time-saver for storyboards. It will make VC initialization type-safe.

What do you think? Should we use it on a daily basis? Should we have a little note with how-to-use section for **SwiftGen**?

**Comment by zummenix** [comment]
It's hard to say without a real project. I would want to see it in action.

**Comment by akhatmullin** [comment]
I really hate code gen tools.

> Sourcery scans your source code, applies your personal templates and generates Swift code for you

If you need templates you can use snippets in Xcode. If you need more templates you can create your own snippets.

**Comment by AgapovOne** [comment]
Now Swift 4.1 can add Equatable itself.
We could remove Sourcery from projects.

Do anyone have any other proposition to use Sourcery for?
@Saritasa/ios

**Comment by zummenix** [comment]
Sourcery can generate an `all` computed property for enums. But this case is very rare.

**Comment by AgapovOne** [comment]
I heard Swift 4.2 would give us `allCases` :)

**Comment by zummenix** [comment]
With swift 4.2 and [Reusable](https://github.com/AliSoftware/Reusable) the need for code gen tools is greatly reduced. Closing.
