### ISSUE TITLE
Code templates/snippets. Common usage for projects

### ISSUE THREAD

**Issue by AgapovOne** [Saritasa/ios-development-guides#40]
All of the projects we do could have a similar codebase.

I would use everywhere a special background view to fix cells background blink.

@Saritasa/ios Do you have suggestions for snippets we could add to the repo to have a quick access to the common code we use everywhere?

I would create a folder and first examples in a repo.

Should we use a framework to include all code inside it and import into our projects?

**Comment by zummenix** [comment]
I'm not sure about framework. Each project is different and has its own helpers/snippets. I'm fond of gradually growing this utilitarian code base for each project separately.
