### ISSUE TITLE
Add a separate document with a list of tools

### ISSUE THREAD

**Issue by zummenix** [Saritasa/ios-development-guides#6]
https://eject.herokuapp.com
Sometimes maybe useful.

**Comment by zummenix** [comment]
https://www.charlesproxy.com to debug http requests.

**Comment by akhatmullin** [comment]
Postman must have.
Sometimes I use browser for work with JSON with JSONViewer.

**Comment by zummenix** [comment]
Yeah, Postman is kind of default to have though for simple requests I prefer curl.

**Comment by AgapovOne** [comment]
https://app.quicktype.io/
Fast JSON to Codable conversion
